include:
  - project: 'allworldit/docker/gitlab-ci-template'
    ref: master
    file: '/default.yml'


test:
  stage: test
  script:
    - docker pull "${CI_IMAGE}"
    - docker run --rm -e CI=true --mount type=bind,source=/tmp,destination=/var/lib/redis "${CI_IMAGE}"
    - docker run --rm -e CI=true -e REDIS_PASSWORD=testpass --mount type=bind,source=/tmp,destination=/var/lib/redis "${CI_IMAGE}"
  artifacts:
    paths:
      - .TIMESTAMP
